[kijanikiosk]
api-staging ansible_host=100.31.247.44
payments-staging ansible_host=3.88.59.135
logs-staging ansible_host=54.211.207.87

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

; ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
; ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
; ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

; server_ips = {
;   "api" = "100.31.247.44"
;   "logs" = "3.88.59.135"
;   "payments" = "54.211.207.87"
; }